### ISSUE TITLE
Unable to run in Node.Js environment

### ISSUE THREAD

**Issue by vladgovor77771** [MetaMask/browser-passworder#11]
Hello, I just tried to run test from Usage example.

```js
const { strict: assert } = require("assert");
const passworder = require("@metamask/browser-passworder");

const secrets = { coolStuff: "all", ssn: "livin large" };
const password = "hunter55";

passworder
  .encrypt(password, secrets)
  .then(function (blob) {
    return passworder.decrypt(password, blob);
  })
  .then(function (result) {
    assert.deepEqual(result, secrets);
  });
```

It is not working because ```global.crypto``` is undefined. What is ```global.crypto``` and how to use this package in Node.js?
Or what are equivalents for this package?

**Comment by vladgovor77771** [comment]
Fixed with
```js
const { Crypto } = require("@peculiar/webcrypto");
global.crypto = new Crypto();
```

**Comment by Gudahtt** [comment]
Glad you found a solution! This library is intended for use in browsers, that is why there are no instructions on getting this to work in Node.js
