### ISSUE TITLE
[Question] If encrypted vault stolen, is password the only key to decrypt?

### ISSUE THREAD

**Issue by ChrisCho-H** [MetaMask/browser-passworder#22]
Hi, thanks for your great open-source!
I've just got a simple question.
In pbkdf2 function, 10,000 rounds of sha256 computation is hard-coded.
In encrypted vault, salt and iv are included without encryption.
So, if this encrypted vault stolen, I guess it will take only minutes for most of human-made password.
Is it correct?
Or did I miss something here?

**Comment by Gudahtt** [comment]
Yes, the vault is encrypted only with a key derived from the user-chosen password. I can't speak to the difficulty in cracking the vault for "typical" passwords, but the rest of what you said sounds accurate to me. We are considering increasing iterations, and adding password restrictions/warnings to encourage users to choose better passwords.
