### ISSUE TITLE
Availability on npm

### ISSUE THREAD

**Issue by refi93** [MetaMask/browser-passworder#6]
When I try `yarn install @metamask/browser-passworder`, it fails with

```
error An unexpected error occurred: "https://registry.yarnpkg.com/@metamask%2fbrowser-passworder: Not found".
```

The package indeed doesn't seem to be published on npm. Are you planning to publish it soon? Is it safe to use the [browser-passworder](https://www.npmjs.com/package/browser-passworder) package which is currently published on npm?

**Comment by Gudahtt** [comment]
`@metamask/browser-passworder` has just been published, so you should now be able to install it.

The `browser-passworder` package is indeed safe to use as well - it's just a bit less up-to-date. See the `CHANGELOG.md` file for all relevant differences.
